/* Create database for replication
*/

USE [master]
GO

/****** Object:  Database [ReplB2BDB]    Script Date: 9/26/2017 10:42:56 AM ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'ReplB2BDB')

DROP DATABASE [ReplB2BDB]
GO

/****** Object:  Database [ReplB2BDB]    Script Date: 9/26/2017 10:42:56 AM ******/
CREATE DATABASE [ReplB2BDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ReplB2BDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.DBINSTANCE1\MSSQL\DATA\ReplB2BDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ReplB2BDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.DBINSTANCE1\MSSQL\DATA\ReplB2BDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [ReplB2BDB] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ReplB2BDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ReplB2BDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ReplB2BDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ReplB2BDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ReplB2BDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ReplB2BDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ReplB2BDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ReplB2BDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ReplB2BDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ReplB2BDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ReplB2BDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ReplB2BDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ReplB2BDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ReplB2BDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ReplB2BDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ReplB2BDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ReplB2BDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ReplB2BDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ReplB2BDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ReplB2BDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ReplB2BDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ReplB2BDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ReplB2BDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ReplB2BDB] SET RECOVERY FULL 
GO

ALTER DATABASE [ReplB2BDB] SET  MULTI_USER 
GO

ALTER DATABASE [ReplB2BDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ReplB2BDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ReplB2BDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ReplB2BDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ReplB2BDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ReplB2BDB] SET QUERY_STORE = OFF
GO

USE [ReplB2BDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [ReplB2BDB] SET  READ_WRITE 
GO


